name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Create .env file
      run: |
        echo "REACT_APP_API_URL=${{ secrets.REACT_APP_LOCAL_API_URL }}" > .env
        echo "REACT_APP_SECRET_KEY=${{ secrets.REACT_APP_PYTHON_API_URL }}" >> .env

    - name: Build project
      run: |
        CI=false npm run build

    - name: Create target directory on EC2
      env:
        EC2_HOST: ${{ secrets.REMOTE_IP }}
        EC2_USER: ${{ secrets.REMOTE_USER }}
        EC2_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
      run: |
        echo "${EC2_KEY}" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USER}@${EC2_HOST} '[ -d /home/ubuntu/build ] && rm -rf /home/ubuntu/build || echo "No directory to delete"'

    - name: Copy files to EC2
      env:
        EC2_HOST: ${{ secrets.REMOTE_IP }}
        EC2_USER: ${{ secrets.REMOTE_USER }}
        EC2_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client
        scp -o StrictHostKeyChecking=no -i key.pem -r ./build ${EC2_USER}@${EC2_HOST}:/home/ubuntu/

